# Generated by Django 5.0.1 on 2025-11-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosestudiante',
            name='apoyo_coorinoco',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datosestudiante',
            name='credito_fes',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datosestudiante',
            name='credito_gobernacion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datosestudiante',
            name='credito_icetex',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datosestudiante',
            name='descuento_asegura_solidaria',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datosestudiante',
            name='descuento_confecoop',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datosestudiante',
            name='descuento_congente',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datosestudiante',
            name='descuento_deporte_cultura',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datosestudiante',
            name='descuento_electoral',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datosestudiante',
            name='descuento_equidad',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datosestudiante',
            name='descuento_excelencia',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datosestudiante',
            name='descuento_hermano_conyuge',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datosestudiante',
            name='descuento_rendimiento_academico',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datosestudiante',
            name='descuento_representante',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datosestudiante',
            name='descuento_socioeconomico',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datosestudiante',
            name='descuento_trabajo_grado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datosestudiante',
            name='ha_solicitado_ayuda_psico',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datosestudiante',
            name='politica_gratuidad',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datosestudiante',
            name='repitio_anio_colegio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datosestudiante',
            name='tiene_hijos',
            field=models.CharField(max_length=50),
        ),
    ]
